export const tracks = [
  {
    id: "analytics",
    label: "Data Analytics",
    icon: "ti-chart-bar",
    color: "#1D9E75",
    bg: "#E1F5EE",
    accent: "#0F6E56",
    tagline: "Turn raw data into business decisions",
    courses: [
      {
        id: "a1",
        title: "SQL for Analysts",
        level: "Beginner",
        duration: "6h",
        lessons: 24,
        tags: ["SQL", "Querying", "Aggregation"],
        desc: "Master SELECT, JOIN, GROUP BY, window functions, and CTEs on real business datasets.",
        popular: true,
      },
      {
        id: "a2",
        title: "Excel & Power Query",
        level: "Beginner",
        duration: "4h",
        lessons: 18,
        tags: ["Excel", "Power Query", "Pivot"],
        desc: "Transform and pivot messy spreadsheets using Power Query's M language.",
      },
      {
        id: "a3",
        title: "Tableau Dashboards",
        level: "Intermediate",
        duration: "8h",
        lessons: 30,
        tags: ["Tableau", "Visualization", "KPIs"],
        desc: "Design executive dashboards tracking real KPIs with calculated fields and LOD expressions.",
        popular: true,
      },
      {
        id: "a4",
        title: "dbt Core Fundamentals",
        level: "Intermediate",
        duration: "7h",
        lessons: 27,
        tags: ["dbt", "SQL", "Modeling"],
        desc: "Build modular, tested, and documented data models in your warehouse using dbt.",
      },
      {
        id: "a5",
        title: "Business Metrics & KPIs",
        level: "Beginner",
        duration: "3h",
        lessons: 12,
        tags: ["Metrics", "Strategy", "Reporting"],
        desc: "Define, track, and communicate ARR, churn, CAC, LTV, and conversion funnels.",
      },
      {
        id: "a6",
        title: "Statistical Analysis with Python",
        level: "Advanced",
        duration: "10h",
        lessons: 38,
        tags: ["Python", "Pandas", "Statistics"],
        desc: "Hypothesis testing, A/B testing, regression, and confidence intervals using real datasets.",
      },
    ],
  },
  {
    id: "engineering",
    label: "Data Engineering",
    icon: "ti-server",
    color: "#378ADD",
    bg: "#E6F1FB",
    accent: "#185FA5",
    tagline: "Build pipelines that power everything",
    courses: [
      {
        id: "e1",
        title: "Python for Data Engineering",
        level: "Beginner",
        duration: "8h",
        lessons: 32,
        tags: ["Python", "Pandas", "Automation"],
        desc: "Write Python scripts to ingest, clean, and load data across APIs, CSVs, and databases.",
        popular: true,
      },
      {
        id: "e2",
        title: "Apache Spark Essentials",
        level: "Intermediate",
        duration: "12h",
        lessons: 44,
        tags: ["Spark", "PySpark", "Distributed"],
        desc: "Process billion-row datasets with PySpark DataFrames, partitioning, and Spark SQL.",
      },
      {
        id: "e3",
        title: "Airflow Pipeline Orchestration",
        level: "Intermediate",
        duration: "9h",
        lessons: 34,
        tags: ["Airflow", "DAGs", "Scheduling"],
        desc: "Design fault-tolerant DAGs with sensors, branching, backfill, and retry logic.",
        popular: true,
      },
      {
        id: "e4",
        title: "Kafka Streaming Architecture",
        level: "Advanced",
        duration: "14h",
        lessons: 52,
        tags: ["Kafka", "Streaming", "Real-time"],
        desc: "Build consumer-producer pipelines and process event streams with Kafka Streams.",
      },
      {
        id: "e5",
        title: "Data Warehouse Design",
        level: "Intermediate",
        duration: "7h",
        lessons: 28,
        tags: ["Snowflake", "BigQuery", "Schema"],
        desc: "Model star schemas, slowly changing dimensions, and partitioned tables in cloud warehouses.",
      },
      {
        id: "e6",
        title: "Docker & Kubernetes for Data",
        level: "Advanced",
        duration: "11h",
        lessons: 40,
        tags: ["Docker", "K8s", "DevOps"],
        desc: "Containerize data apps and deploy Spark/Airflow clusters on Kubernetes.",
      },
    ],
  },
  {
    id: "science",
    label: "Data Science",
    icon: "ti-atom",
    color: "#BA7517",
    bg: "#FAEEDA",
    accent: "#854F0B",
    tagline: "Discover patterns, build predictive models",
    courses: [
      {
        id: "s1",
        title: "Machine Learning Fundamentals",
        level: "Intermediate",
        duration: "14h",
        lessons: 56,
        tags: ["Python", "Scikit-learn", "ML"],
        desc: "Regression, classification, clustering, cross-validation, and feature engineering from scratch.",
        popular: true,
      },
      {
        id: "s2",
        title: "Pandas & NumPy Mastery",
        level: "Beginner",
        duration: "6h",
        lessons: 24,
        tags: ["Pandas", "NumPy", "EDA"],
        desc: "Wrangle messy real-world datasets using vectorized operations, merges, and reshaping.",
      },
      {
        id: "s3",
        title: "Feature Engineering",
        level: "Intermediate",
        duration: "8h",
        lessons: 30,
        tags: ["Features", "Encoding", "Selection"],
        desc: "Transform raw data into high-signal features: encoding, scaling, imputation, and selection.",
      },
      {
        id: "s4",
        title: "Time Series Forecasting",
        level: "Advanced",
        duration: "10h",
        lessons: 38,
        tags: ["ARIMA", "Prophet", "Forecasting"],
        desc: "Forecast sales, traffic, and demand with ARIMA, Prophet, and LSTM approaches.",
        popular: true,
      },
      {
        id: "s5",
        title: "Data Visualization with Plotly",
        level: "Beginner",
        duration: "5h",
        lessons: 20,
        tags: ["Plotly", "Seaborn", "Charts"],
        desc: "Create interactive charts and dashboards with Plotly Express and Matplotlib.",
      },
      {
        id: "s6",
        title: "Causal Inference & Experimentation",
        level: "Advanced",
        duration: "12h",
        lessons: 46,
        tags: ["A/B Testing", "Causality", "DoE"],
        desc: "Design experiments and apply diff-in-diff, propensity scoring, and synthetic control.",
      },
    ],
  },
  {
    id: "ai",
    label: "AI Specialist",
    icon: "ti-brain",
    color: "#D4537E",
    bg: "#FBEAF0",
    accent: "#993556",
    tagline: "Deploy AI that solves real problems",
    courses: [
      {
        id: "ai1",
        title: "LLM APIs & Prompt Engineering",
        level: "Beginner",
        duration: "5h",
        lessons: 20,
        tags: ["LLMs", "Prompting", "APIs"],
        desc: "Call OpenAI, Anthropic, and open-source LLMs with structured outputs and system prompts.",
        popular: true,
      },
      {
        id: "ai2",
        title: "RAG Pipelines with Vector Databases",
        level: "Intermediate",
        duration: "9h",
        lessons: 34,
        tags: ["RAG", "Embeddings", "Pinecone"],
        desc: "Build retrieval-augmented generation apps using embeddings, chunking, and Pinecone/Weaviate.",
      },
      {
        id: "ai3",
        title: "Fine-tuning Language Models",
        level: "Advanced",
        duration: "12h",
        lessons: 44,
        tags: ["Fine-tuning", "LoRA", "PEFT"],
        desc: "Adapt open-source LLMs to domain-specific tasks with LoRA, PEFT, and instruction tuning.",
        popular: true,
      },
      {
        id: "ai4",
        title: "AI Agents & Tool Use",
        level: "Advanced",
        duration: "10h",
        lessons: 38,
        tags: ["Agents", "LangChain", "Tools"],
        desc: "Build autonomous agents that call APIs, write code, browse the web, and manage tasks.",
      },
      {
        id: "ai5",
        title: "Computer Vision with PyTorch",
        level: "Intermediate",
        duration: "11h",
        lessons: 42,
        tags: ["PyTorch", "CNN", "Detection"],
        desc: "Train and deploy image classifiers and object detectors using modern CNN architectures.",
      },
      {
        id: "ai6",
        title: "MLOps & Model Deployment",
        level: "Intermediate",
        duration: "9h",
        lessons: 36,
        tags: ["MLflow", "FastAPI", "CI/CD"],
        desc: "Package, version, serve, and monitor ML models in production using MLflow and FastAPI.",
      },
    ],
  },
];

export const stats = [
  { label: "Courses", value: "24", icon: "ti-books" },
  { label: "Hands-on Projects", value: "80+", icon: "ti-code" },
  { label: "Real Datasets", value: "150+", icon: "ti-database" },
  { label: "Job-ready Skills", value: "100%", icon: "ti-briefcase" },
];

export const levels = ["All", "Beginner", "Intermediate", "Advanced"];
